from __future__ import annotations

from typing import Any

_GLOSSARY: dict[str, dict[str, Any]] = {
    # ── Trend ──────────────────────────────────────────────────────────────
    "sma_20": {
        "id": "sma_20",
        "name": "SMA(20)",
        "full_name": "Simple Moving Average (20)",
        "category": "Trend",
        "description": "Average closing price over the last 20 trading days.",
        "formula": "SMA = sum(close, 20) / 20",
        "source": "close",
        "period": "20",
        "implemented": True,
    },
    "sma_50": {
        "id": "sma_50",
        "name": "SMA(50)",
        "full_name": "Simple Moving Average (50)",
        "category": "Trend",
        "description": "Average closing price over the last 50 trading days. A common intermediate-term trend benchmark.",
        "formula": "SMA = sum(close, 50) / 50",
        "source": "close",
        "period": "50",
        "implemented": True,
    },
    "sma_200": {
        "id": "sma_200",
        "name": "SMA(200)",
        "full_name": "Simple Moving Average (200)",
        "category": "Trend",
        "description": "Average closing price over the last 200 trading days. Widely viewed as the long-term trend line.",
        "formula": "SMA = sum(close, 200) / 200",
        "source": "close",
        "period": "200",
        "implemented": True,
    },
    "ema_12": {
        "id": "ema_12",
        "name": "EMA(12)",
        "full_name": "Exponential Moving Average (12)",
        "category": "Trend",
        "description": "Exponentially weighted moving average giving more weight to recent prices over 12 periods.",
        "formula": "EMA = close x A + EMA_prev x (1 - A) where A = 2 / (12 + 1)",
        "source": "close",
        "period": "12",
        "implemented": True,
    },
    "ema_26": {
        "id": "ema_26",
        "name": "EMA(26)",
        "full_name": "Exponential Moving Average (26)",
        "category": "Trend",
        "description": "Exponentially weighted moving average over 26 periods, typically used as the slow MACD input.",
        "formula": "EMA = close x A + EMA_prev x (1 - A) where A = 2 / (26 + 1)",
        "source": "close",
        "period": "26",
        "implemented": True,
    },
    "wma": {
        "id": "wma",
        "name": "WMA",
        "full_name": "Weighted Moving Average",
        "category": "Trend",
        "description": "Linear-weighted moving average where most recent price receives highest weight.",
        "formula": "WMA = sum(close_i x i) / sum(i) for i = 1..N",
        "source": "close",
        "period": "Configurable",
        "implemented": True,
    },
    "kama": {
        "id": "kama",
        "name": "KAMA",
        "full_name": "Kaufman Adaptive Moving Average",
        "category": "Trend",
        "description": "Adaptive MA that adjusts smoothing based on the Efficiency Ratio. Smooths in ranging markets, responds quickly in trends.",
        "formula": "KAMA = KAMA_prev + SC x (close - KAMA_prev) where SC = [ER x (fast - slow) + slow]^2",
        "source": "close",
        "period": "10, 2, 30 (ER, fast, slow)",
        "implemented": True,
    },
    "macd": {
        "id": "macd",
        "name": "MACD",
        "full_name": "Moving Average Convergence Divergence",
        "category": "Trend",
        "description": "Difference between fast (12) and slow (26) EMAs. Positive values indicate short-term momentum above the long-term average.",
        "formula": "MACD = EMA(close, 12) - EMA(close, 26)",
        "source": "close",
        "period": "12 / 26",
        "implemented": True,
    },
    "macd_ema": {
        "id": "macd_ema",
        "name": "MACD Signal",
        "full_name": "MACD Signal Line",
        "category": "Trend",
        "description": "9-period EMA of the MACD line. A bullish crossover occurs when MACD crosses above its signal line.",
        "formula": "MACD_ema = EMA(MACD_line, 9)",
        "source": "close",
        "period": "9",
        "implemented": True,
    },
    "macd_hist": {
        "id": "macd_hist",
        "name": "MACD Hist",
        "full_name": "MACD Histogram",
        "category": "Trend",
        "description": "Difference between MACD and its signal line. Positive and increasing = accelerating upward momentum.",
        "formula": "MACD_hist = MACD_line - MACD_ema",
        "source": "close",
        "period": "12 / 26 / 9",
        "implemented": True,
    },
    "ppo": {
        "id": "ppo",
        "name": "PPO",
        "full_name": "Percentage Price Oscillator",
        "category": "Trend",
        "description": "Like MACD but expressed as a percentage of the slow EMA, enabling cross-asset comparison.",
        "formula": "PPO = (EMA(fast) - EMA(slow)) / EMA(slow) x 100",
        "source": "close",
        "period": "12 / 26 / 9",
        "implemented": True,
    },
    "ppo_signal": {
        "id": "ppo_signal",
        "name": "PPO Signal",
        "full_name": "PPO Signal Line",
        "category": "Trend",
        "description": "EMA of the PPO line. Bullish crossover when PPO crosses above its signal line.",
        "formula": "PPO_signal = EMA(PPO, 9)",
        "source": "close",
        "period": "9",
        "implemented": True,
    },
    "ppo_histogram": {
        "id": "ppo_histogram",
        "name": "PPO Hist",
        "full_name": "PPO Histogram",
        "category": "Trend",
        "description": "Difference between PPO and its signal line. Receding histogram = momentum fading.",
        "formula": "PPO_hist = PPO - PPO_signal",
        "source": "close",
        "period": "12 / 26 / 9",
        "implemented": True,
    },
    "trix": {
        "id": "trix",
        "name": "TRIX",
        "full_name": "Triple Smoothed Exponential Average",
        "category": "Trend",
        "description": "Triple-smoothed EMA of close followed by a 1-period rate of change. Filters out short-term noise to reveal the underlying trend.",
        "formula": "TRIX = ROC(EMA(EMA(EMA(close, N), N), N), 1)",
        "source": "close",
        "period": "15",
        "implemented": True,
    },
    "adx": {
        "id": "adx",
        "name": "ADX",
        "full_name": "Average Directional Index",
        "category": "Trend",
        "description": "Measures trend strength regardless of direction. Above 25 = strong trend; below 20 = ranging market.",
        "formula": "ADX = EMA(100 x |+DI - -DI| / (+DI + -DI), 14)",
        "source": "high, low, close",
        "period": "14",
        "implemented": True,
    },
    "di_plus": {
        "id": "di_plus",
        "name": "DI+",
        "full_name": "Positive Directional Indicator",
        "category": "Trend",
        "description": "Measures the strength of upward price movement. Part of the ADX system.",
        "formula": "+DI = 100 x EMA(+DM, 14) / EMA(ATR, 14)",
        "source": "high, low, close",
        "period": "14",
        "implemented": True,
    },
    "di_minus": {
        "id": "di_minus",
        "name": "DI-",
        "full_name": "Negative Directional Indicator",
        "category": "Trend",
        "description": "Measures the strength of downward price movement. Part of the ADX system.",
        "formula": "-DI = 100 x EMA(-DM, 14) / EMA(ATR, 14)",
        "source": "high, low, close",
        "period": "14",
        "implemented": True,
    },
    "aroon_up": {
        "id": "aroon_up",
        "name": "Aroon Up",
        "full_name": "Aroon Up",
        "category": "Trend",
        "description": "Measures how many periods since the most recent N-period high. High values = recent new high.",
        "formula": "Aroon_Up = 100 x (N - periods_since_high) / N",
        "source": "high",
        "period": "25",
        "implemented": True,
    },
    "aroon_down": {
        "id": "aroon_down",
        "name": "Aroon Down",
        "full_name": "Aroon Down",
        "category": "Trend",
        "description": "Measures how many periods since the most recent N-period low. High values = recent new low.",
        "formula": "Aroon_Down = 100 x (N - periods_since_low) / N",
        "source": "low",
        "period": "25",
        "implemented": True,
    },
    "aroon_osc": {
        "id": "aroon_osc",
        "name": "Aroon Osc",
        "full_name": "Aroon Oscillator",
        "category": "Trend",
        "description": "Aroon Up minus Aroon Down. Positive values indicate uptrend bias; negative values indicate downtrend bias.",
        "formula": "Aroon_Osc = Aroon_Up - Aroon_Down",
        "source": "high, low",
        "period": "25",
        "implemented": True,
    },
    "ma_stack": {
        "id": "ma_stack",
        "name": "MA Stack",
        "full_name": "Moving Average Stack",
        "category": "Trend",
        "description": "Relative ordering of short (20), medium (50), and long-term (200) moving averages. Bullish when 20 > 50 > 200.",
        "formula": "Compare SMA(20), SMA(50), SMA(200) ordering",
        "source": "close",
        "period": "20 / 50 / 200",
        "implemented": True,
    },
    "ma_slope": {
        "id": "ma_slope",
        "name": "MA Slope",
        "full_name": "Moving Average Slope",
        "category": "Trend",
        "description": "Rate of change of a moving average over a backward-looking window. Steep positive = accelerating uptrend.",
        "formula": "MA_Slope = (MA(t) - MA(t - N)) / N",
        "source": "close",
        "period": "Configurable",
        "implemented": True,
    },
    "linreg_slope": {
        "id": "linreg_slope",
        "name": "LinReg Slope",
        "full_name": "Linear Regression Slope",
        "category": "Trend",
        "description": "Slope coefficient from fitting a line to closing prices over N periods. Positive = upward drift.",
        "formula": "B = sum((t - mean_t) x (close - mean_c)) / sum((t - mean_t)^2)",
        "source": "close",
        "period": "20",
        "implemented": True,
    },
    "linreg_channel": {
        "id": "linreg_channel",
        "name": "LinReg Channel",
        "full_name": "Linear Regression Channel",
        "category": "Trend",
        "description": "Linear regression line with parallel bands at +/- N standard deviations. Forms a trend channel.",
        "formula": "Channel = LinReg(close, N) +/- k x StdErr",
        "source": "close",
        "period": "20",
        "implemented": True,
    },
    # ── Momentum ───────────────────────────────────────────────────────────
    "rsi": {
        "id": "rsi",
        "name": "RSI",
        "full_name": "Relative Strength Index",
        "category": "Momentum",
        "description": "Measures speed and magnitude of recent price changes. Overbought above 70; oversold below 30.",
        "formula": "RSI = 100 - 100 / (1 + avg_gain / avg_loss)",
        "source": "close",
        "period": "14",
        "implemented": True,
    },
    "stoch_k": {
        "id": "stoch_k",
        "name": "Stoch %K",
        "full_name": "Stochastic Oscillator %K",
        "category": "Momentum",
        "description": "Compares close to the high-low range. Above 80 = overbought; below 20 = oversold.",
        "formula": "%K = 100 x (close - low(N)) / (high(N) - low(N))",
        "source": "high, low, close",
        "period": "14 / 3",
        "implemented": True,
    },
    "stoch_d": {
        "id": "stoch_d",
        "name": "Stoch %D",
        "full_name": "Stochastic Oscillator %D (Signal)",
        "category": "Momentum",
        "description": "3-period SMA of %K. Crossover of %K above %D is a bullish signal.",
        "formula": "%D = SMA(%K, 3)",
        "source": "high, low, close",
        "period": "3",
        "implemented": True,
    },
    "stoch_rsi": {
        "id": "stoch_rsi",
        "name": "Stoch RSI",
        "full_name": "Stochastic RSI",
        "category": "Momentum",
        "description": "Applies the stochastic formula to RSI values, making it more sensitive to RSI extremes.",
        "formula": "Stoch_RSI = (RSI - min(RSI, 14)) / (max(RSI, 14) - min(RSI, 14))",
        "source": "close",
        "period": "14",
        "implemented": True,
    },
    "williams_r": {
        "id": "williams_r",
        "name": "Williams %R",
        "full_name": "Williams Percent Range",
        "category": "Momentum",
        "description": "Inverse of stochastic oscillator. Below -80 = oversold; above -20 = overbought.",
        "formula": "%R = -100 x (high(N) - close) / (high(N) - low(N))",
        "source": "high, low, close",
        "period": "14",
        "implemented": True,
    },
    "cci": {
        "id": "cci",
        "name": "CCI",
        "full_name": "Commodity Channel Index",
        "category": "Momentum",
        "description": "Measures deviation of typical price from its SMA. Above +100 = overbought; below -100 = oversold.",
        "formula": "CCI = (TP - SMA(TP, 20)) / (0.015 x MeanAbsDev(TP))",
        "source": "high, low, close",
        "period": "20",
        "implemented": True,
    },
    "tsi": {
        "id": "tsi",
        "name": "TSI",
        "full_name": "True Strength Index",
        "category": "Momentum",
        "description": "Double-smoothed rate of change measuring momentum with reduced noise.",
        "formula": "TSI = 100 x EMA(EMA(momentum, N), M) / EMA(EMA(|momentum|, N), M)",
        "source": "close",
        "period": "25 / 13",
        "implemented": True,
    },
    "ultimate_osc": {
        "id": "ultimate_osc",
        "name": "Ultimate Osc",
        "full_name": "Ultimate Oscillator",
        "category": "Momentum",
        "description": "Weighted multi-timeframe oscillator designed to capture momentum across short, medium, and long horizons.",
        "formula": "UO = 100 x (4xBP(7) + 2xBP(14) + BP(28)) / (4xTR(7) + 2xTR(14) + TR(28))",
        "source": "high, low, close",
        "period": "7 / 14 / 28",
        "implemented": True,
    },
    "cmo": {
        "id": "cmo",
        "name": "CMO",
        "full_name": "Chande Momentum Oscillator",
        "category": "Momentum",
        "description": "Momentum oscillator comparing sum of upward vs downward price changes. Ranges from -100 to +100.",
        "formula": "CMO = 100 x (sum_up - sum_down) / (sum_up + sum_down)",
        "source": "close",
        "period": "14",
        "implemented": True,
    },
    "bop": {
        "id": "bop",
        "name": "BoP",
        "full_name": "Balance of Power",
        "category": "Momentum",
        "description": "Measures the ability of buyers vs sellers to control price within the session range.",
        "formula": "BoP = (close - open) / (high - low)",
        "source": "open, high, low, close",
        "period": "N/A",
        "implemented": True,
    },
    "roc": {
        "id": "roc",
        "name": "ROC",
        "full_name": "Rate of Change",
        "category": "Momentum",
        "description": "Percentage change in closing price over N periods. Positive = price increasing.",
        "formula": "ROC = (close / close(N_ago) - 1) x 100",
        "source": "close",
        "period": "12",
        "implemented": True,
    },
    "chop": {
        "id": "chop",
        "name": "CHOP",
        "full_name": "Choppiness Index",
        "category": "Momentum",
        "description": "Measures whether the market is trending or ranging. Above 61.8 = ranging; below 38.2 = trending.",
        "formula": "CHOP = 100 x log10(sum(ATR, N) / (high(N) - low(N))) / log10(N)",
        "source": "high, low, close",
        "period": "14",
        "implemented": True,
    },
    "rsi_divergence": {
        "id": "rsi_divergence",
        "name": "RSI Diverg",
        "full_name": "RSI Divergence",
        "category": "Momentum",
        "description": "Bullish divergence: price makes lower low while RSI makes higher low. Bearish divergence: price makes higher high while RSI makes lower high.",
        "formula": "Compare price and RSI swing highs/lows",
        "source": "close",
        "period": "14",
        "implemented": True,
    },
    # ── Volatility ─────────────────────────────────────────────────────────
    "bb_upper": {
        "id": "bb_upper",
        "name": "BB Upper",
        "full_name": "Bollinger Band Upper",
        "category": "Volatility",
        "description": "SMA(20) + 2 standard deviations. Acts as dynamic resistance during trending moves.",
        "formula": "Upper = SMA(close, 20) + 2 x Std(close, 20)",
        "source": "close",
        "period": "20 / 2",
        "implemented": True,
    },
    "bb_middle": {
        "id": "bb_middle",
        "name": "BB Mid",
        "full_name": "Bollinger Band Middle (SMA)",
        "category": "Volatility",
        "description": "The 20-period SMA serving as the central reference for Bollinger Bands.",
        "formula": "Middle = SMA(close, 20)",
        "source": "close",
        "period": "20",
        "implemented": True,
    },
    "bb_lower": {
        "id": "bb_lower",
        "name": "BB Lower",
        "full_name": "Bollinger Band Lower",
        "category": "Volatility",
        "description": "SMA(20) - 2 standard deviations. Acts as dynamic support during trending moves.",
        "formula": "Lower = SMA(close, 20) - 2 x Std(close, 20)",
        "source": "close",
        "period": "20 / 2",
        "implemented": True,
    },
    "percent_b": {
        "id": "percent_b",
        "name": "%B",
        "full_name": "Percent B",
        "category": "Volatility",
        "description": "Price position within the Bollinger Bands. 1.0 = at upper band, 0.0 = at lower band, 0.5 = at middle.",
        "formula": "%B = (close - lower) / (upper - lower)",
        "source": "close",
        "period": "20",
        "implemented": True,
    },
    "bandwidth": {
        "id": "bandwidth",
        "name": "Bandwidth",
        "full_name": "Bollinger Bandwidth",
        "category": "Volatility",
        "description": "Width of the Bollinger Bands relative to the middle band. Narrow bandwidth often precedes volatility expansion.",
        "formula": "BW = (upper - lower) / middle",
        "source": "close",
        "period": "20",
        "implemented": True,
    },
    "bb_squeeze": {
        "id": "bb_squeeze",
        "name": "BB Squeeze",
        "full_name": "Bollinger Squeeze",
        "category": "Volatility",
        "description": "True when Bandwidth contracts below a 6-month minimum, suggesting a pending breakout.",
        "formula": "BW < min(BW, 126) AND Keltner lower > BB lower AND Keltner upper < BB upper",
        "source": "close",
        "period": "20",
        "implemented": True,
    },
    "keltner_upper": {
        "id": "keltner_upper",
        "name": "Keltner Up",
        "full_name": "Keltner Channel Upper",
        "category": "Volatility",
        "description": "EMA(20) + 2 x ATR(10). An ATR-based volatility band similar to Bollinger Bands.",
        "formula": "Upper = EMA(close, 20) + 2 x ATR(10)",
        "source": "high, low, close",
        "period": "20 / 10 / 2",
        "implemented": True,
    },
    "keltner_mid": {
        "id": "keltner_mid",
        "name": "Keltner Mid",
        "full_name": "Keltner Channel Middle (EMA)",
        "category": "Volatility",
        "description": "The 20-period EMA central reference for Keltner Channels.",
        "formula": "Middle = EMA(close, 20)",
        "source": "close",
        "period": "20",
        "implemented": True,
    },
    "keltner_lower": {
        "id": "keltner_lower",
        "name": "Keltner Low",
        "full_name": "Keltner Channel Lower",
        "category": "Volatility",
        "description": "EMA(20) - 2 x ATR(10). Lower ATR-based volatility band.",
        "formula": "Lower = EMA(close, 20) - 2 x ATR(10)",
        "source": "high, low, close",
        "period": "20 / 10 / 2",
        "implemented": True,
    },
    "atr": {
        "id": "atr",
        "name": "ATR",
        "full_name": "Average True Range",
        "category": "Volatility",
        "description": "Average of the true range over 14 periods. Measures absolute price volatility.",
        "formula": "TR = max(H-L, |H-C_prev|, |L-C_prev|); ATR = SMA(TR, 14)",
        "source": "high, low, close",
        "period": "14",
        "implemented": True,
    },
    "atr_pct": {
        "id": "atr_pct",
        "name": "ATR%",
        "full_name": "ATR as % of Close",
        "category": "Volatility",
        "description": "ATR normalized by closing price, enabling cross-asset volatility comparison.",
        "formula": "ATR% = ATR / close x 100",
        "source": "high, low, close",
        "period": "14",
        "implemented": True,
    },
    "true_range": {
        "id": "true_range",
        "name": "True Range",
        "full_name": "True Range",
        "category": "Volatility",
        "description": "The widest of: current high-low range, absolute distance from high to previous close, or low to previous close.",
        "formula": "TR = max(H-L, |H-C_prev|, |L-C_prev|)",
        "source": "high, low, close",
        "period": "1",
        "implemented": True,
    },
    "std_dev": {
        "id": "std_dev",
        "name": "Std Dev",
        "full_name": "Standard Deviation",
        "category": "Volatility",
        "description": "Rolling standard deviation of closing price. Used in Bollinger Bands and as a raw volatility measure.",
        "formula": "s = sqrt(sum((close - SMA)^2, N) / (N - 1))",
        "source": "close",
        "period": "20",
        "implemented": True,
    },
    "realized_vol_21": {
        "id": "realized_vol_21",
        "name": "RV(21)",
        "full_name": "Realized Volatility (21d)",
        "category": "Volatility",
        "description": "Annualized volatility of daily log returns over 21 trading days (~1 month).",
        "formula": "RV = s(log_return, 21) x sqrt(252)",
        "source": "close",
        "period": "21",
        "implemented": True,
    },
    "realized_vol_63": {
        "id": "realized_vol_63",
        "name": "RV(63)",
        "full_name": "Realized Volatility (63d)",
        "category": "Volatility",
        "description": "Annualized volatility of daily log returns over 63 trading days (~3 months).",
        "formula": "RV = s(log_return, 63) x sqrt(252)",
        "source": "close",
        "period": "63",
        "implemented": True,
    },
    "range_expansion": {
        "id": "range_expansion",
        "name": "Range Exp",
        "full_name": "Range Expansion / Contraction",
        "category": "Volatility",
        "description": "Ratio of current true range to average true range. Above 1.0 = expanding volatility.",
        "formula": "RE = TR / ATR(N)",
        "source": "high, low, close",
        "period": "14",
        "implemented": True,
    },
    "donchian_upper": {
        "id": "donchian_upper",
        "name": "Donchian Up",
        "full_name": "Donchian Channel Upper",
        "category": "Volatility",
        "description": "Highest high over N periods. The upper boundary of a Donchian Channel.",
        "formula": "Upper = rolling_max(high, 20)",
        "source": "high",
        "period": "20",
        "implemented": True,
    },
    "donchian_lower": {
        "id": "donchian_lower",
        "name": "Donchian Low",
        "full_name": "Donchian Channel Lower",
        "category": "Volatility",
        "description": "Lowest low over N periods. The lower boundary of a Donchian Channel.",
        "formula": "Lower = rolling_min(low, 20)",
        "source": "low",
        "period": "20",
        "implemented": True,
    },
    "donchian_middle": {
        "id": "donchian_middle",
        "name": "Donchian Mid",
        "full_name": "Donchian Channel Middle",
        "category": "Volatility",
        "description": "Midpoint of the Donchian Channel: (upper + lower) / 2.",
        "formula": "Middle = (Upper + Lower) / 2",
        "source": "high, low",
        "period": "20",
        "implemented": True,
    },
    # ── Volume ─────────────────────────────────────────────────────────────
    "obv": {
        "id": "obv",
        "name": "OBV",
        "full_name": "On-Balance Volume",
        "category": "Volume",
        "description": "Cumulative total of volume adjusted by price direction. Rising OBV suggests accumulation.",
        "formula": "OBV = OBV_prev + volume x sign(close - close_prev)",
        "source": "close, volume",
        "period": "N/A",
        "implemented": True,
    },
    "obv_slope": {
        "id": "obv_slope",
        "name": "OBV Slope",
        "full_name": "OBV Slope (20d)",
        "category": "Volume",
        "description": "Linear slope of OBV over 20 periods. Positive = OBV trending up, suggesting accumulation pressure.",
        "formula": "Linear regression slope of OBV over 20 periods",
        "source": "close, volume",
        "period": "20",
        "implemented": True,
    },
    "vwap": {
        "id": "vwap",
        "name": "VWAP",
        "full_name": "Volume-Weighted Average Price",
        "category": "Volume",
        "description": "Cumulative typical price x volume divided by cumulative volume. Represents the average traded price.",
        "formula": "VWAP = sum(TP x volume) / sum(volume)",
        "source": "high, low, close, volume",
        "period": "N/A",
        "implemented": True,
    },
    "rvol": {
        "id": "rvol",
        "name": "RVOL",
        "full_name": "Relative Volume",
        "category": "Volume",
        "description": "Ratio of current volume to its 20-period average. Above 2.0 = significantly above average volume.",
        "formula": "RVOL = volume / SMA(volume, 20)",
        "source": "volume",
        "period": "20",
        "implemented": True,
    },
    "dollar_volume": {
        "id": "dollar_volume",
        "name": "Dol Vol",
        "full_name": "Dollar Volume",
        "category": "Volume",
        "description": "Close x volume. The total monetary value traded in the session.",
        "formula": "DolVol = close x volume",
        "source": "close, volume",
        "period": "N/A",
        "implemented": True,
    },
    "avg_dollar_volume": {
        "id": "avg_dollar_volume",
        "name": "aDol Vol",
        "full_name": "Average Dollar Volume (20d)",
        "category": "Volume",
        "description": "Rolling 20-period average of dollar volume. A measure of typical liquidity.",
        "formula": "aDolVol = SMA(close x volume, 20)",
        "source": "close, volume",
        "period": "20",
        "implemented": True,
    },
    "volume_spike": {
        "id": "volume_spike",
        "name": "Vol Spike",
        "full_name": "Volume Spike Detection",
        "category": "Volume",
        "description": "True when volume exceeds its trailing average by more than 2.5 standard deviations.",
        "formula": "Volume > SMA(vol, 20) + 2.5 x Std(vol, 20)",
        "source": "volume",
        "period": "20",
        "implemented": True,
    },
    "ad_line": {
        "id": "ad_line",
        "name": "A/D Line",
        "full_name": "Accumulation / Distribution Line",
        "category": "Volume",
        "description": "Cumulative measure of where close falls within the high-low range, weighted by volume.",
        "formula": "A/D = A/D_prev + volume x (close - low - (high - close)) / (high - low)",
        "source": "high, low, close, volume",
        "period": "N/A",
        "implemented": True,
    },
    "cmf": {
        "id": "cmf",
        "name": "CMF",
        "full_name": "Chaikin Money Flow",
        "category": "Volume",
        "description": "A/D summed over 20 periods divided by total volume. Above 0 = buying pressure; below 0 = selling.",
        "formula": "CMF = sum(MFV, 20) / sum(volume, 20)",
        "source": "high, low, close, volume",
        "period": "20",
        "implemented": True,
    },
    "chaikin_osc": {
        "id": "chaikin_osc",
        "name": "Chaikin Osc",
        "full_name": "Chaikin Oscillator",
        "category": "Volume",
        "description": "3-period EMA of A/D minus 10-period EMA of A/D. Crossovers signal shifts in buying/selling pressure.",
        "formula": "Chaikin = EMA(A/D, 3) - EMA(A/D, 10)",
        "source": "high, low, close, volume",
        "period": "3 / 10",
        "implemented": True,
    },
    "mfi": {
        "id": "mfi",
        "name": "MFI",
        "full_name": "Money Flow Index",
        "category": "Volume",
        "description": "Volume-weighted RSI. Overbought above 80; oversold below 20.",
        "formula": "MFI = 100 - 100 / (1 + pos_MF / neg_MF)",
        "source": "high, low, close, volume",
        "period": "14",
        "implemented": True,
    },
    "vpt": {
        "id": "vpt",
        "name": "VPT",
        "full_name": "Volume Price Trend",
        "category": "Volume",
        "description": "Cumulative total of volume weighted by percentage price change. Combines volume confirmation with trend.",
        "formula": "VPT = VPT_prev + volume x (close - close_prev) / close_prev",
        "source": "close, volume",
        "period": "N/A",
        "implemented": True,
    },
    "force_index": {
        "id": "force_index",
        "name": "Force Idx",
        "full_name": "Force Index",
        "category": "Volume",
        "description": "Price change x volume. Measures the power behind a price move. Typically smoothed with an EMA.",
        "formula": "Force = (close - close_prev) x volume",
        "source": "close, volume",
        "period": "13",
        "implemented": True,
    },
    "eom": {
        "id": "eom",
        "name": "EOM",
        "full_name": "Ease of Movement",
        "category": "Volume",
        "description": "Relates price movement to volume. High values = price moved easily (low volume); low = difficulty (high volume).",
        "formula": "EOM = ((H+L)/2 - (H_prev+L_prev)/2) / (volume / 10000)",
        "source": "high, low, volume",
        "period": "14",
        "implemented": True,
    },
    # ── Structure ──────────────────────────────────────────────────────────
    "return_1d": {
        "id": "return_1d",
        "name": "Ret(1d)",
        "full_name": "1-Day Return",
        "category": "Structure",
        "description": "Simple 1-day percentage change in closing price.",
        "formula": "R = close / close_prev - 1",
        "source": "close",
        "period": "1",
        "implemented": True,
    },
    "return_5d": {
        "id": "return_5d",
        "name": "Ret(5d)",
        "full_name": "5-Day Return",
        "category": "Structure",
        "description": "Simple 5-day percentage change in closing price.",
        "formula": "R = close / close(-5) - 1",
        "source": "close",
        "period": "5",
        "implemented": True,
    },
    "return_21d": {
        "id": "return_21d",
        "name": "Ret(21d)",
        "full_name": "21-Day Return",
        "category": "Structure",
        "description": "Simple 21-day percentage change in closing price (~1 month).",
        "formula": "R = close / close(-21) - 1",
        "source": "close",
        "period": "21",
        "implemented": True,
    },
    "return_63d": {
        "id": "return_63d",
        "name": "Ret(63d)",
        "full_name": "63-Day Return",
        "category": "Structure",
        "description": "Simple 63-day percentage change in closing price (~3 months).",
        "formula": "R = close / close(-63) - 1",
        "source": "close",
        "period": "63",
        "implemented": True,
    },
    "return_126": {
        "id": "return_126",
        "name": "Ret(126d)",
        "full_name": "126-Day Return",
        "category": "Structure",
        "description": "Simple 126-day percentage change in closing price (~6 months).",
        "formula": "R = close / close(-126) - 1",
        "source": "close",
        "period": "126",
        "implemented": True,
    },
    "return_252": {
        "id": "return_252",
        "name": "Ret(252d)",
        "full_name": "252-Day Return",
        "category": "Structure",
        "description": "Simple 252-day percentage change in closing price (~1 year).",
        "formula": "R = close / close(-252) - 1",
        "source": "close",
        "period": "252",
        "implemented": True,
    },
    "log_return": {
        "id": "log_return",
        "name": "Log Ret",
        "full_name": "Log Return",
        "category": "Structure",
        "description": "Natural logarithm of the price ratio. Used in volatility calculations and statistical models.",
        "formula": "LogR = ln(close / close_prev)",
        "source": "close",
        "period": "1",
        "implemented": True,
    },
    "gap_pct": {
        "id": "gap_pct",
        "name": "Gap%",
        "full_name": "Overnight Gap",
        "category": "Structure",
        "description": "Percentage change from previous close to current open. Positive = gap up; negative = gap down.",
        "formula": "Gap% = (open / close_prev - 1) x 100",
        "source": "close, open",
        "period": "N/A",
        "implemented": True,
    },
    "gap_fill": {
        "id": "gap_fill",
        "name": "Gap Fill",
        "full_name": "Gap Fill Detection",
        "category": "Structure",
        "description": "True if price retraces to fill the gap between previous close and current open within N periods.",
        "formula": "Compare subsequent highs/lows to gap range",
        "source": "open, high, low, close",
        "period": "N/A",
        "implemented": True,
    },
    "pct_off_52w_high": {
        "id": "pct_off_52w_high",
        "name": "%Off Hi",
        "full_name": "% Off 52-Week High",
        "category": "Structure",
        "description": "Percentage below the rolling 252-period maximum high. Negative = below the high.",
        "formula": "%Off = close / rolling_max(high, 252) - 1",
        "source": "close, high",
        "period": "252",
        "implemented": True,
    },
    "pct_off_52w_low": {
        "id": "pct_off_52w_low",
        "name": "%Off Lo",
        "full_name": "% Off 52-Week Low",
        "category": "Structure",
        "description": "Percentage above the rolling 252-period minimum low. Positive = above the low.",
        "formula": "%Off = close / rolling_min(low, 252) - 1",
        "source": "close, low",
        "period": "252",
        "implemented": True,
    },
    "is_new_52w_high": {
        "id": "is_new_52w_high",
        "name": "N52wH",
        "full_name": "New 52-Week High",
        "category": "Structure",
        "description": "True when current high equals the 252-period maximum high.",
        "formula": "high == rolling_max(high, 252)",
        "source": "high",
        "period": "252",
        "implemented": True,
    },
    "is_new_52w_low": {
        "id": "is_new_52w_low",
        "name": "N52wL",
        "full_name": "New 52-Week Low",
        "category": "Structure",
        "description": "True when current low equals the 252-period minimum low.",
        "formula": "low == rolling_min(low, 252)",
        "source": "low",
        "period": "252",
        "implemented": True,
    },
    "dist_to_ma": {
        "id": "dist_to_ma",
        "name": "Dist MA",
        "full_name": "Distance to Moving Average",
        "category": "Structure",
        "description": "Relative distance of closing price from its moving average. Positive = price above MA.",
        "formula": "Distance = (close / MA - 1) x 100",
        "source": "close",
        "period": "Configurable",
        "implemented": True,
    },
    "above_ma": {
        "id": "above_ma",
        "name": "Above MA",
        "full_name": "Above Moving Average",
        "category": "Structure",
        "description": "True when closing price is above a given moving average.",
        "formula": "close > MA",
        "source": "close",
        "period": "Configurable",
        "implemented": True,
    },
    "inside_bar": {
        "id": "inside_bar",
        "name": "Inside Bar",
        "full_name": "Inside Bar",
        "category": "Structure",
        "description": "True when current high <= previous high AND current low >= previous low. Indicates consolidation.",
        "formula": "high <= high(-1) AND low >= low(-1)",
        "source": "high, low",
        "period": "N/A",
        "implemented": True,
    },
    "outside_bar": {
        "id": "outside_bar",
        "name": "Outside Bar",
        "full_name": "Outside Bar",
        "category": "Structure",
        "description": "True when current high > previous high AND current low < previous low. Indicates breakout / expansion.",
        "formula": "high > high(-1) AND low < low(-1)",
        "source": "high, low",
        "period": "N/A",
        "implemented": True,
    },
    "pivot_points": {
        "id": "pivot_points",
        "name": "Pivots",
        "full_name": "Pivot Points (S/R)",
        "category": "Structure",
        "description": "Local swing highs (resistance) and lows (support) identified over a rolling window.",
        "formula": "Pivot High: high(N+M) < high(N) > high(N-M). Pivot Low: inverse.",
        "source": "high, low",
        "period": "5 / 5 (left / right)",
        "implemented": True,
    },
    # ── Relative Performance ───────────────────────────────────────────────
    "beta_20d": {
        "id": "beta_20d",
        "name": "Beta(20)",
        "full_name": "Beta vs SPY (20d)",
        "category": "Relative Performance",
        "description": "Covariance of stock return with SPY return, divided by variance of SPY return, over 20 days.",
        "formula": "Beta = cov(R_stock, R_SPY) / var(R_SPY)",
        "source": "close (SPY required)",
        "period": "20",
        "implemented": True,
    },
    "beta_60d": {
        "id": "beta_60d",
        "name": "Beta(60)",
        "full_name": "Beta vs SPY (60d)",
        "category": "Relative Performance",
        "description": "Covariance of stock return with SPY return, divided by variance of SPY return, over 60 days.",
        "formula": "Beta = cov(R_stock, R_SPY) / var(R_SPY)",
        "source": "close (SPY required)",
        "period": "60",
        "implemented": True,
    },
    "alpha": {
        "id": "alpha",
        "name": "Alpha",
        "full_name": "Alpha vs SPY",
        "category": "Relative Performance",
        "description": "Excess return of the stock not explained by market beta. Positive Alpha = outperformance relative to SPY risk.",
        "formula": "Alpha = R_stock - (RFR + Beta x (R_SPY - RFR))",
        "source": "close (SPY required)",
        "period": "20 / 60",
        "implemented": True,
    },
    "rs_spy": {
        "id": "rs_spy",
        "name": "RS vs SPY",
        "full_name": "Relative Strength vs SPY",
        "category": "Relative Performance",
        "description": "Ratio of stock return to SPY return over the period. Above 1.0 = outperformance.",
        "formula": "RS = (1 + R_stock) / (1 + R_SPY) - 1",
        "source": "close (SPY required)",
        "period": "20 / 60",
        "implemented": True,
    },
    "corr_spy": {
        "id": "corr_spy",
        "name": "Corr SPY",
        "full_name": "Rolling Correlation vs SPY",
        "category": "Relative Performance",
        "description": "Pearson correlation of daily returns with SPY over a rolling window. Measures how closely the stock tracks the market.",
        "formula": "Corr = cov(R_stock, R_SPY) / (s(R_stock) x s(R_SPY))",
        "source": "close (SPY required)",
        "period": "60",
        "implemented": True,
    },
    # ── Utility ────────────────────────────────────────────────────────────
    "synthetic_mode": {
        "id": "synthetic_mode",
        "name": "Synthetic",
        "full_name": "Synthetic Mode",
        "category": "Utility",
        "description": "True when the lake is running with synthetic (demo) data instead of live API data.",
        "formula": "Config flag: [lake] synthetic_mode",
        "source": "config",
        "period": "N/A",
        "implemented": True,
    },
    "data_health": {
        "id": "data_health",
        "name": "Health",
        "full_name": "Data Health Status",
        "category": "Utility",
        "description": "Quality status of the most recent bar data: valid, stale, degraded, or quarantined.",
        "formula": "Read from latest bar quality_status",
        "source": "lake_bars",
        "period": "N/A",
        "implemented": True,
    },
    "trading_dates": {
        "id": "trading_dates",
        "name": "Trading N",
        "full_name": "Trading Date Count",
        "category": "Utility",
        "description": "Number of trading days available for a symbol. Useful to verify sufficient data for indicator computation.",
        "formula": "COUNT(DISTINCT effective_date)",
        "source": "lake_bars",
        "period": "N/A",
        "implemented": True,
    },
}
